
services:
    xpress_tek_zc.form.type.calendar:
        class: XpressTek\ZCBundle\Form\CalendarType
        tags:
            - { name: form.type, alias: calendar}
            
    xpress_tek_zc.form.type.event:
        class: XpressTek\ZCBundle\Form\EventType
        tags:
            - { name: form.type, alias: event}
#    xpress_tek_zc.example:
#        class: %xpress_tek_zc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
